// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using NutshellBlog.Data;
using System;

namespace NutshellBlog.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180326024417_InitDatabase")]
    partial class InitDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("NutshellBlog.Models.Archives", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool?>("IsDeleted");

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("T_Archives");
                });

            modelBuilder.Entity("NutshellBlog.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ArchivesId");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2147483647);

                    b.Property<string>("Description");

                    b.Property<string>("Identity")
                        .HasMaxLength(100);

                    b.Property<bool?>("IsDeleted");

                    b.Property<DateTime?>("LastEditTime");

                    b.Property<DateTime?>("PublishTime");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("ArchivesId");

                    b.ToTable("T_Articles");
                });

            modelBuilder.Entity("NutshellBlog.Models.ArticleTag", b =>
                {
                    b.Property<int>("ArticleId");

                    b.Property<int>("TagId");

                    b.HasKey("ArticleId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("T_Article_Tag");
                });

            modelBuilder.Entity("NutshellBlog.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool?>("IsDeleted");

                    b.Property<string>("Label");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("NutshellBlog.Models.Article", b =>
                {
                    b.HasOne("NutshellBlog.Models.Archives", "Archives")
                        .WithMany("Articles")
                        .HasForeignKey("ArchivesId");
                });

            modelBuilder.Entity("NutshellBlog.Models.ArticleTag", b =>
                {
                    b.HasOne("NutshellBlog.Models.Article", "Article")
                        .WithMany("ArticleTags")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NutshellBlog.Models.Tag", "Tag")
                        .WithMany("ArticleTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
